import type { EstimatorAnalysis, EstimatorFormData } from "./estimator-types";

// Color constants matching the brand
const NAVY = [10, 22, 40] as const;
const ELECTRIC_BLUE = [45, 127, 249] as const;
const WHITE = [255, 255, 255] as const;
const SILVER = [192, 200, 212] as const;
const LIGHT_GRAY = [232, 236, 241] as const;

function formatCurrency(amount: number): string {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(amount);
}

export async function generateEstimatorPDF(
  analysis: EstimatorAnalysis,
  formData: EstimatorFormData,
): Promise<void> {
  const { default: jsPDF } = await import("jspdf");
  const doc = new jsPDF("p", "mm", "a4");
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = 0;

  function addPage() {
    doc.addPage();
    y = margin;
  }

  function checkPageBreak(needed: number) {
    if (y + needed > 270) {
      addPage();
    }
  }

  function addFooter() {
    const pages = doc.getNumberOfPages();
    for (let i = 1; i <= pages; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(...SILVER);
      doc.text(
        "Generated by SchemaSync.AI | schemasync.ai",
        pageWidth / 2,
        287,
        { align: "center" },
      );
      doc.text(`Page ${i} of ${pages}`, pageWidth - margin, 287, {
        align: "right",
      });
    }
  }

  // ========== PAGE 1: Title Page ==========
  // Background header
  doc.setFillColor(...NAVY);
  doc.rect(0, 0, pageWidth, 100, "F");

  // Brand
  doc.setFontSize(28);
  doc.setTextColor(...ELECTRIC_BLUE);
  doc.text("SchemaSync.AI", margin, 40);

  doc.setFontSize(12);
  doc.setTextColor(...WHITE);
  doc.text("Schema Complexity Report", margin, 52);

  // Date
  doc.setFontSize(10);
  doc.setTextColor(...SILVER);
  doc.text(new Date().toLocaleDateString("en-US", { dateStyle: "long" }), margin, 65);

  // Client info
  doc.setFontSize(10);
  doc.text(
    `Prepared for ${formData.firstName} ${formData.lastName} | ${formData.company}`,
    margin,
    80,
  );

  // Complexity Score
  y = 120;
  doc.setFontSize(16);
  doc.setTextColor(50, 50, 50);
  doc.text("Overall Complexity Score", margin, y);

  y += 12;
  doc.setFontSize(48);
  doc.setTextColor(...ELECTRIC_BLUE);
  doc.text(`${analysis.complexityScore.toFixed(1)}`, margin, y);

  doc.setFontSize(14);
  doc.setTextColor(100, 100, 100);
  doc.text(`/ 10  —  ${analysis.complexityLabel}`, margin + 42, y);

  y += 12;
  doc.setFontSize(10);
  doc.setTextColor(80, 80, 80);
  const explanationLines = doc.splitTextToSize(
    analysis.complexityExplanation,
    contentWidth,
  );
  doc.text(explanationLines, margin, y);
  y += explanationLines.length * 5 + 10;

  // Dimensional scores table
  doc.setFontSize(14);
  doc.setTextColor(50, 50, 50);
  doc.text("Complexity Breakdown", margin, y);
  y += 8;

  const dimensions = [
    ["System Heterogeneity", analysis.dimensionalScores.systemHeterogeneity],
    ["Data Volume", analysis.dimensionalScores.dataVolume],
    ["Integration Risk", analysis.dimensionalScores.integrationRisk],
    ["Timeline Pressure", analysis.dimensionalScores.timelinePressure],
    ["Data Quality Risk", analysis.dimensionalScores.dataQuality],
    ["Compliance Overhead", analysis.dimensionalScores.complianceOverhead],
    ["Documentation Gap", analysis.dimensionalScores.documentationGap],
  ] as const;

  for (const [label, score] of dimensions) {
    doc.setFontSize(9);
    doc.setTextColor(80, 80, 80);
    doc.text(label, margin, y + 4);

    // Bar background
    const barX = margin + 50;
    const barWidth = contentWidth - 65;
    doc.setFillColor(230, 230, 230);
    doc.roundedRect(barX, y, barWidth, 5, 2, 2, "F");

    // Bar fill
    const fillWidth = (score / 10) * barWidth;
    if (score <= 3) doc.setFillColor(34, 197, 94);
    else if (score <= 6) doc.setFillColor(234, 179, 8);
    else doc.setFillColor(239, 68, 68);
    doc.roundedRect(barX, y, fillWidth, 5, 2, 2, "F");

    // Score number
    doc.setTextColor(50, 50, 50);
    doc.text(`${score}/10`, pageWidth - margin, y + 4, { align: "right" });

    y += 9;
  }

  // ========== PAGE 2: Risk Assessment ==========
  addPage();

  doc.setFontSize(16);
  doc.setTextColor(50, 50, 50);
  doc.text("Risk Assessment", margin, y);
  y += 10;

  doc.setFontSize(10);
  doc.setTextColor(80, 80, 80);
  const narrativeLines = doc.splitTextToSize(analysis.riskNarrative, contentWidth);
  doc.text(narrativeLines, margin, y);
  y += narrativeLines.length * 5 + 12;

  // Risk Factors
  checkPageBreak(60);
  doc.setFontSize(14);
  doc.setTextColor(50, 50, 50);
  doc.text("Top Risk Factors", margin, y);
  y += 8;

  for (const risk of analysis.riskFactors) {
    checkPageBreak(30);

    // Severity badge
    doc.setFontSize(8);
    if (risk.severity === "high") doc.setTextColor(239, 68, 68);
    else if (risk.severity === "medium") doc.setTextColor(234, 179, 8);
    else doc.setTextColor(34, 197, 94);
    doc.text(`[${risk.severity.toUpperCase()}]`, margin, y);

    // Title
    doc.setFontSize(11);
    doc.setTextColor(50, 50, 50);
    doc.text(risk.title, margin + 22, y);
    y += 6;

    // Description
    doc.setFontSize(9);
    doc.setTextColor(100, 100, 100);
    const descLines = doc.splitTextToSize(risk.description, contentWidth - 5);
    doc.text(descLines, margin + 5, y);
    y += descLines.length * 4.5 + 6;
  }

  // ========== PAGE 3: Cost & Effort ==========
  checkPageBreak(80);
  if (y > margin + 10) {
    doc.setDrawColor(220, 220, 220);
    doc.line(margin, y, pageWidth - margin, y);
    y += 10;
  }

  doc.setFontSize(14);
  doc.setTextColor(50, 50, 50);
  doc.text("Effort Estimate", margin, y);
  y += 8;

  doc.setFontSize(20);
  doc.setTextColor(...ELECTRIC_BLUE);
  doc.text(
    `${analysis.effortEstimate.min} - ${analysis.effortEstimate.max} ${analysis.effortEstimate.unit}`,
    margin,
    y,
  );
  y += 8;

  doc.setFontSize(10);
  doc.setTextColor(80, 80, 80);
  const rationaleLines = doc.splitTextToSize(
    analysis.effortEstimate.rationale,
    contentWidth,
  );
  doc.text(rationaleLines, margin, y);
  y += rationaleLines.length * 5 + 12;

  // Cost comparison
  checkPageBreak(60);
  doc.setFontSize(14);
  doc.setTextColor(50, 50, 50);
  doc.text("Cost Comparison", margin, y);
  y += 10;

  // Table header
  doc.setFillColor(...LIGHT_GRAY);
  doc.rect(margin, y - 4, contentWidth, 8, "F");
  doc.setFontSize(9);
  doc.setTextColor(50, 50, 50);
  doc.text("Approach", margin + 3, y);
  doc.text("Cost Range", margin + 65, y);
  doc.text("Timeframe", margin + 120, y);
  y += 10;

  // Consultant row
  doc.setFontSize(9);
  doc.setTextColor(80, 80, 80);
  doc.text("Traditional Consulting", margin + 3, y);
  doc.text(
    `${formatCurrency(analysis.costComparison.consultant.low)} - ${formatCurrency(analysis.costComparison.consultant.high)}`,
    margin + 65,
    y,
  );
  doc.text(analysis.costComparison.consultant.timeframe, margin + 120, y);
  y += 8;

  // Automated row
  doc.setTextColor(...ELECTRIC_BLUE);
  doc.text("Automated (SchemaSync)", margin + 3, y);
  doc.text(
    `${formatCurrency(analysis.costComparison.automated.low)} - ${formatCurrency(analysis.costComparison.automated.high)}`,
    margin + 65,
    y,
  );
  doc.text(analysis.costComparison.automated.timeframe, margin + 120, y);
  y += 10;

  doc.setFontSize(10);
  doc.text(
    `Potential savings: up to ${analysis.costComparison.savingsPercentage}%`,
    margin,
    y,
  );
  y += 15;

  // ========== PAGE 4: Recommendations ==========
  checkPageBreak(60);
  doc.setDrawColor(220, 220, 220);
  doc.line(margin, y, pageWidth - margin, y);
  y += 10;

  doc.setFontSize(14);
  doc.setTextColor(50, 50, 50);
  doc.text("5 Questions to Answer Before Starting", margin, y);
  y += 8;

  doc.setFontSize(9);
  doc.setTextColor(80, 80, 80);
  for (let i = 0; i < analysis.preIntegrationQuestions.length; i++) {
    checkPageBreak(15);
    const qLines = doc.splitTextToSize(
      `${i + 1}. ${analysis.preIntegrationQuestions[i]}`,
      contentWidth - 5,
    );
    doc.text(qLines, margin + 3, y);
    y += qLines.length * 4.5 + 3;
  }
  y += 8;

  // Red flags
  if (analysis.redFlags.length > 0) {
    checkPageBreak(30);
    doc.setFontSize(14);
    doc.setTextColor(50, 50, 50);
    doc.text("Red Flags", margin, y);
    y += 8;

    doc.setFontSize(9);
    doc.setTextColor(200, 120, 0);
    for (const flag of analysis.redFlags) {
      checkPageBreak(12);
      const flagLines = doc.splitTextToSize(`! ${flag}`, contentWidth - 5);
      doc.text(flagLines, margin + 3, y);
      y += flagLines.length * 4.5 + 3;
    }
    y += 8;
  }

  // Next steps
  checkPageBreak(40);
  doc.setFontSize(14);
  doc.setTextColor(50, 50, 50);
  doc.text("Recommended First Steps", margin, y);
  y += 8;

  doc.setFontSize(9);
  doc.setTextColor(80, 80, 80);
  for (let i = 0; i < analysis.recommendedFirstSteps.length; i++) {
    checkPageBreak(15);
    const sLines = doc.splitTextToSize(
      `${i + 1}. ${analysis.recommendedFirstSteps[i]}`,
      contentWidth - 5,
    );
    doc.text(sLines, margin + 3, y);
    y += sLines.length * 4.5 + 3;
  }

  // Add footers
  addFooter();

  // Save
  doc.save("schema-complexity-report.pdf");
}
